// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeInOneMinute.Repository.DataContexts;

#nullable disable

namespace ResumeInOneMinute.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208125016_AddDailyTokenLimit")]
    partial class AddDailyTokenLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.MasterValue", b =>
                {
                    b.Property<long>("MasterValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("master_value_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MasterValueId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MasterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("master_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("MasterValueId")
                        .HasName("pk_master_values");

                    b.HasIndex("MasterType", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_master_values_master_type_code");

                    b.ToTable("master_values", "master");

                    b.HasData(
                        new
                        {
                            MasterValueId = 1L,
                            Code = "FREE",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1362),
                            DisplayName = "Free",
                            IsActive = true,
                            MasterType = "PLAN_CODE",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 2L,
                            Code = "PRO",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1365),
                            DisplayName = "Pro",
                            IsActive = true,
                            MasterType = "PLAN_CODE",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 3L,
                            Code = "ENTERPRISE",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1366),
                            DisplayName = "Enterprise",
                            IsActive = true,
                            MasterType = "PLAN_CODE",
                            SortOrder = 3
                        },
                        new
                        {
                            MasterValueId = 4L,
                            Code = "MONTHLY",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1367),
                            DisplayName = "Monthly",
                            IsActive = true,
                            MasterType = "BILLING_CYCLE",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 5L,
                            Code = "YEARLY",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1368),
                            DisplayName = "Yearly",
                            IsActive = true,
                            MasterType = "BILLING_CYCLE",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 6L,
                            Code = "INR",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1369),
                            DisplayName = "Indian Rupee",
                            IsActive = true,
                            MasterType = "CURRENCY",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 7L,
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1370),
                            DisplayName = "US Dollar",
                            IsActive = true,
                            MasterType = "CURRENCY",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 8L,
                            Code = "ACTIVE",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1371),
                            DisplayName = "Active",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_STATUS",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 9L,
                            Code = "CANCELLED",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1372),
                            DisplayName = "Cancelled",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_STATUS",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 10L,
                            Code = "EXPIRED",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1374),
                            DisplayName = "Expired",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_STATUS",
                            SortOrder = 3
                        },
                        new
                        {
                            MasterValueId = 11L,
                            Code = "PAUSED",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1375),
                            DisplayName = "Paused",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_STATUS",
                            SortOrder = 4
                        },
                        new
                        {
                            MasterValueId = 12L,
                            Code = "UPGRADE",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1376),
                            DisplayName = "Upgrade",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_CHANGE_TYPE",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 13L,
                            Code = "DOWNGRADE",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1377),
                            DisplayName = "Downgrade",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_CHANGE_TYPE",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 14L,
                            Code = "RENEWAL",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1378),
                            DisplayName = "Renewal",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_CHANGE_TYPE",
                            SortOrder = 3
                        },
                        new
                        {
                            MasterValueId = 15L,
                            Code = "CANCEL",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1380),
                            DisplayName = "Cancel",
                            IsActive = true,
                            MasterType = "SUBSCRIPTION_CHANGE_TYPE",
                            SortOrder = 4
                        },
                        new
                        {
                            MasterValueId = 16L,
                            Code = "PENDING",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1381),
                            DisplayName = "Pending",
                            IsActive = true,
                            MasterType = "PAYMENT_STATUS",
                            SortOrder = 1
                        },
                        new
                        {
                            MasterValueId = 17L,
                            Code = "SUCCESS",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1382),
                            DisplayName = "Success",
                            IsActive = true,
                            MasterType = "PAYMENT_STATUS",
                            SortOrder = 2
                        },
                        new
                        {
                            MasterValueId = 18L,
                            Code = "FAILED",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1383),
                            DisplayName = "Failed",
                            IsActive = true,
                            MasterType = "PAYMENT_STATUS",
                            SortOrder = 3
                        },
                        new
                        {
                            MasterValueId = 19L,
                            Code = "RAZORPAY",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1385),
                            DisplayName = "Razorpay",
                            IsActive = true,
                            MasterType = "PAYMENT_PROVIDER",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.PlanBenefit", b =>
                {
                    b.Property<long>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("benefit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BenefitId"));

                    b.Property<string>("BenefitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("benefit_code");

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("benefit_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("BenefitId")
                        .HasName("pk_plan_benefits");

                    b.ToTable("plan_benefits", "billing");

                    b.HasData(
                        new
                        {
                            BenefitId = 1L,
                            BenefitCode = "TEMPLATE_LIMIT",
                            BenefitName = "Template Limit",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1529),
                            Description = "Number of templates allowed",
                            IsActive = true
                        },
                        new
                        {
                            BenefitId = 2L,
                            BenefitCode = "RATE_LIMIT_PER_MINUTE",
                            BenefitName = "Rate Limit",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1531),
                            Description = "API requests per minute",
                            IsActive = true
                        },
                        new
                        {
                            BenefitId = 3L,
                            BenefitCode = "DAILY_TOKEN_LIMIT",
                            BenefitName = "Daily Token Limit",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1532),
                            Description = "Total instruction message characters per day",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.PlanBenefitMap", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MapId"));

                    b.Property<long>("BenefitId")
                        .HasColumnType("bigint")
                        .HasColumnName("benefit_id");

                    b.Property<string>("BenefitValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("benefit_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.HasKey("MapId")
                        .HasName("pk_plan_benefit_map");

                    b.HasIndex("BenefitId")
                        .HasDatabaseName("ix_plan_benefit_map_benefit_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_plan_benefit_map_plan_id");

                    b.ToTable("plan_benefit_map", "billing");

                    b.HasData(
                        new
                        {
                            MapId = 1L,
                            BenefitId = 1L,
                            BenefitValue = "3",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1559),
                            PlanId = 1L
                        },
                        new
                        {
                            MapId = 2L,
                            BenefitId = 2L,
                            BenefitValue = "30",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1561),
                            PlanId = 1L
                        },
                        new
                        {
                            MapId = 5L,
                            BenefitId = 3L,
                            BenefitValue = "3000",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1562),
                            PlanId = 1L
                        },
                        new
                        {
                            MapId = 3L,
                            BenefitId = 1L,
                            BenefitValue = "50",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1563),
                            PlanId = 2L
                        },
                        new
                        {
                            MapId = 4L,
                            BenefitId = 2L,
                            BenefitValue = "300",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1564),
                            PlanId = 2L
                        },
                        new
                        {
                            MapId = 6L,
                            BenefitId = 3L,
                            BenefitValue = "10000",
                            CreatedAt = new DateTime(2026, 2, 8, 12, 50, 15, 716, DateTimeKind.Utc).AddTicks(1565),
                            PlanId = 2L
                        });
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<long>("PaymentProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_provider_id");

                    b.Property<long>("PaymentStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_status_id");

                    b.Property<long>("PlanPriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_price_id");

                    b.Property<string>("ProviderOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_order_id");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_payment_id");

                    b.Property<Guid?>("UserSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("PaymentId")
                        .HasName("pk_subscription_payments");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_subscription_payments_currency_id");

                    b.HasIndex("PaymentProviderId")
                        .HasDatabaseName("ix_subscription_payments_payment_provider_id");

                    b.HasIndex("PaymentStatusId")
                        .HasDatabaseName("ix_subscription_payments_payment_status_id");

                    b.HasIndex("PlanPriceId")
                        .HasDatabaseName("ix_subscription_payments_plan_price_id");

                    b.HasIndex("UserSubscriptionId")
                        .HasDatabaseName("ix_subscription_payments_user_subscription_id");

                    b.ToTable("subscription_payments", "billing");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPlan", b =>
                {
                    b.Property<long>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("PlanCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_code_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_name");

                    b.HasKey("PlanId")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("PlanCodeId")
                        .HasDatabaseName("ix_subscription_plans_plan_code_id");

                    b.ToTable("subscription_plans", "billing");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPlanPrice", b =>
                {
                    b.Property<long>("PlanPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("plan_price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlanPriceId"));

                    b.Property<long>("BillingCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_cycle_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("PlanPriceId")
                        .HasName("pk_subscription_plan_prices");

                    b.HasIndex("BillingCycleId")
                        .HasDatabaseName("ix_subscription_plan_prices_billing_cycle_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_subscription_plan_prices_currency_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscription_plan_prices_plan_id");

                    b.ToTable("subscription_plan_prices", "billing");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("GlobalUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("global_user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiry_time");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<byte[]>("RefreshTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_hash");

                    b.Property<byte[]>("RefreshTokenSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GlobalUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_global_user_id");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserProfile", b =>
                {
                    b.Property<long>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserProfileId"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("GlobalUserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("global_user_profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserProfileId")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles", "auth");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_subscription_id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("GlobalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_user_id");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<long>("PlanPriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_price_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserSubscriptionId")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_user_subscriptions_plan_id");

                    b.HasIndex("PlanPriceId")
                        .HasDatabaseName("ix_user_subscriptions_plan_price_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_user_subscriptions_status_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_subscriptions_user_id");

                    b.ToTable("user_subscriptions", "billing");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserSubscriptionHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<long>("ChangeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("change_type_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'UTC')");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<long>("NewPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("new_plan_id");

                    b.Property<long>("NewPlanPriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("new_plan_price_id");

                    b.Property<long?>("OldPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("old_plan_id");

                    b.Property<long?>("OldPlanPriceId")
                        .HasColumnType("bigint")
                        .HasColumnName("old_plan_price_id");

                    b.Property<Guid>("UserSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("HistoryId")
                        .HasName("pk_user_subscription_history");

                    b.HasIndex("ChangeTypeId")
                        .HasDatabaseName("ix_user_subscription_history_change_type_id");

                    b.HasIndex("UserSubscriptionId")
                        .HasDatabaseName("ix_user_subscription_history_user_subscription_id");

                    b.ToTable("user_subscription_history", "billing");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.PlanBenefitMap", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.PlanBenefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_benefit_map_plan_benefits_benefit_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.SubscriptionPlan", "Plan")
                        .WithMany("Benefits")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_benefit_map_subscription_plans_plan_id");

                    b.Navigation("Benefit");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPayment", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_master_values_currency_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "PaymentProvider")
                        .WithMany()
                        .HasForeignKey("PaymentProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_master_values_payment_provider_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_master_values_payment_status_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.SubscriptionPlanPrice", "PlanPrice")
                        .WithMany()
                        .HasForeignKey("PlanPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_payments_subscription_plan_prices_plan_price_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId")
                        .HasConstraintName("fk_subscription_payments_user_subscriptions_user_subscription_");

                    b.Navigation("Currency");

                    b.Navigation("PaymentProvider");

                    b.Navigation("PaymentStatus");

                    b.Navigation("PlanPrice");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPlan", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "PlanCode")
                        .WithMany()
                        .HasForeignKey("PlanCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_plans_master_values_plan_code_id");

                    b.Navigation("PlanCode");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPlanPrice", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "BillingCycle")
                        .WithMany()
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_plan_prices_master_values_billing_cycle_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_plan_prices_master_values_currency_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_plan_prices_subscription_plans_plan_id");

                    b.Navigation("BillingCycle");

                    b.Navigation("Currency");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserProfile", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("ResumeInOneMinute.Domain.Model.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserSubscription", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_subscription_plans_plan_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.SubscriptionPlanPrice", "PlanPrice")
                        .WithMany()
                        .HasForeignKey("PlanPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_subscription_plan_prices_plan_price_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_master_values_status_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("PlanPrice");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.UserSubscriptionHistory", b =>
                {
                    b.HasOne("ResumeInOneMinute.Domain.Model.MasterValue", "ChangeType")
                        .WithMany()
                        .HasForeignKey("ChangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscription_history_master_values_change_type_id");

                    b.HasOne("ResumeInOneMinute.Domain.Model.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscription_history_user_subscriptions_user_subscript");

                    b.Navigation("ChangeType");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.SubscriptionPlan", b =>
                {
                    b.Navigation("Benefits");
                });

            modelBuilder.Entity("ResumeInOneMinute.Domain.Model.User", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
